export const products = [
    {
        id: 1,
        title: "Samsung S21",
        description: "black in color",
        price: 2500,
        img: "./Images/samsung-s21-ulta.png",
        quantity:1,
    },
    {
        id: 2,
        title: "iphoneX",
        description: "gold in color",
        price: 50000,
        img: "./Images/iphoneX.jpg",
        quantity:1,
    },
    {
        id: 3,
        title: "Redmi9",
        description: "white in color",
        price: 12000,
        img: "./Images/redmi9.jpg",
        quantity:1,
    },
    {
        id: 4,
        title: "Samsung-m21",
        description: "blue in color",
        price: 18000,
        img: "./Images/samsung-m21.jpg",
        quantity:1,
    },
    {
        id: 5,
        title: "vivo-v23",
        description: "rose gold in color",
        price: 2500,
        img: "./Images/vivo-v23.jpg",
        quantity:1,
    },
]